import "@/app/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { getDictionary } from "@/dictionaries";
import type { Metadata } from "next";
import { Libre_Baskerville, Plus_Jakarta_Sans } from "next/font/google";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-deco",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const dict = await getDictionary(params.lang);
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${libreBaskerville.variable} font-sans antialiased bg-beige-1 overflow-x-hidden`}
      >
        <Header
          lang={params.lang}
          links={dict.footer.links}
          contacts={dict.footer.contacts}
          buttons={dict.buttons}
        />
        {children}
        <Footer lang={params.lang} />
      </body>
    </html>
  );
}
